const pousadas = [
  { name:'Centro Class', address:'R. Rui Barbosa, 08 - Centro, Armação dos Búzios - RJ', map:'https://maps.app.goo.gl/sF6QJmEnK5qKA7ji8', photos:'https://photos.app.goo.gl/HizRbSCCoEL75sqh9', cloudbeds:'http://hotels.cloudbeds.com/connect/208581#/calendar', color:'blue' },
  { name:'Casa Centro', address:'R. Rui Barbosa, 390 A - Lot. Triangulo de Buzios, Armação dos Búzios', map:'https://maps.app.goo.gl/guP7PDbX854PmhmZ6', photos:'https://photos.app.goo.gl/3JPDo4cmN8kzXSZU6', cloudbeds:'http://hotels.cloudbeds.com/connect/207758#/calendar', color:'terracotta' },
  { name:'Centro Up', address:'R. Rui Barbosa, 229 A - Lot. Triangulo de Buzios, Armação dos Búzios', map:'https://maps.app.goo.gl/8LPvmBV2XCA1wKNP9', photos:'https://photos.app.goo.gl/dpSKEJCMKNFF7jJE7', cloudbeds:'http://hotels.cloudbeds.com/connect/209202#/calendar', color:'sage' },
  { name:'Solar João Fernandes', address:'Rua São Cristóvão, R. João Fernandes, 16, Armação dos Búzios - RJ', map:'https://maps.app.goo.gl/qszQTRjtk92Pnfkn6', photos:'https://photos.app.goo.gl/ez61zesWzVXZFh388', cloudbeds:'http://hotels.cloudbeds.com/connect/239462#/calendar', color:'sand' }
];
const feriados = [
  ['2026-09-07','Independência do Brasil'],['2026-10-12','Nossa Senhora Aparecida'],['2026-11-02','Finados'],['2026-11-15','Proclamação da República'],['2026-11-20','Consciência Negra'],['2026-12-25','Natal'],['2027-01-01','Confraternização Universal']
];
const brl = value => Number(value || 0).toLocaleString('pt-BR',{style:'currency',currency:'BRL'});
const $ = id => document.getElementById(id);
let viewDate = new Date(2026,7,20), selectedLoft = 1;

function renderProperties(){ $('propertyGrid').innerHTML = pousadas.map((p,i)=>`<a class="property ${p.color}" href="${p.cloudbeds}" target="_blank" rel="noopener"><span class="property-number">0${i+1}</span><h3>${p.name}</h3><p>Cloudbeds · calendário</p><span class="open">Abrir painel ↗</span></a>`).join(''); $('quoteProperty').innerHTML = pousadas.map((p,i)=>`<option value="${i}">${p.name}</option>`).join(''); }
function dateLabel(date){ return date.toLocaleDateString('pt-BR',{day:'2-digit',month:'2-digit',year:'numeric'}); }
function renderCalendar(){ const month=viewDate.getMonth(), year=viewDate.getFullYear(); $('monthLabel').textContent=viewDate.toLocaleDateString('pt-BR',{month:'long',year:'numeric'}); const first=(new Date(year,month,1).getDay()+6)%7, total=new Date(year,month+1,0).getDate(); let html=''; for(let i=0;i<first;i++) html+='<span class="day empty"></span>'; for(let day=1;day<=total;day++){ const key=`${year}-${String(month+1).padStart(2,'0')}-${String(day).padStart(2,'0')}`, holiday=feriados.find(x=>x[0]===key), today=key==='2026-08-20'; html+=`<button class="day ${holiday?'holiday':''} ${today?'today':''}" title="${holiday?holiday[1]:''}">${day}${holiday?'<i></i>':''}</button>`; } $('calendarGrid').innerHTML=html; const upcoming=feriados.filter(x=>new Date(x[0]+'T12:00:00')>=viewDate).slice(0,3); $('eventsList').innerHTML=upcoming.map(x=>{const d=new Date(x[0]+'T12:00:00');return `<div class="event"><strong>${String(d.getDate()).padStart(2,'0')}<small>${d.toLocaleDateString('pt-BR',{month:'short'}).replace('.','').toUpperCase()}</small></strong><span>${x[1]}<small>Feriado nacional</small></span></div>`}).join(''); const next=feriados.find(x=>new Date(x[0]+'T12:00:00')>=new Date(2026,7,20)); $('nextHoliday').textContent=next?`${new Date(next[0]+'T12:00:00').toLocaleDateString('pt-BR',{day:'2-digit',month:'long'})} · ${next[1]}`:''; $('selectedHoliday').textContent=upcoming[0]?upcoming[0][1]:''; }
function parseQuote(text){ const dateMatch=text.match(/([A-Za-zÀ-ÿ]{3,9}),?\s*([A-Za-zÀ-ÿ]{3,9})\.?\s*(\d{1,2})(?:\/([0-9]{1,2})\/([0-9]{4}))?\s*-\s*([A-Za-zÀ-ÿ]{3,9}),?\s*([A-Za-zÀ-ÿ]{3,9})\.?\s*(\d{1,2})(?:\/([0-9]{1,2})\/([0-9]{4}))?/i); const totalMatch=text.match(/Total da Acomodação\s*:?\s*(?:R\$\s*)?([\d.,]+)/i); if(!dateMatch||!totalMatch) throw new Error('Não encontrei as datas e o Total da Acomodação.'); const months={jan:0,fev:1,mar:2,abr:3,mai:4,jun:5,jul:6,ago:7,set:8,out:9,nov:10,dez:11}; const year=Number(dateMatch[5]||dateMatch[10]||2026), startMonth=months[dateMatch[2].slice(0,3).toLowerCase()], endMonth=months[dateMatch[7].slice(0,3).toLowerCase()]; const start=new Date(year,startMonth,Number(dateMatch[3])), end=new Date(Number(dateMatch[10]||year),endMonth,Number(dateMatch[8])); if(end<=start) end.setFullYear(start.getFullYear()+1); const money=totalMatch[1].includes(',')?totalMatch[1].replace(/\./g,'').replace(',','.'):totalMatch[1].replace(/,/g,''); return {start,end,nights:Math.max(1,Math.round((end-start)/86400000)),total:Number(money),startWeek:dateMatch[1],endWeek:dateMatch[6]}; }
function generateQuote(){ try{ const p=pousadas[Number($('quoteProperty').value)], q=parseQuote($('quoteInput').value), guests=$('quoteGuests').value, room=$('quoteRoom').value; const text=`🏡 POUSADA ${p.name.toUpperCase()}\n📍 Endereço: ${p.address}\n📍 Localização: ${p.map}\n\n🛏️ ${room}\n\n📅 Datas da Estadia\n➡️ Check-in: ${q.startWeek}, ${dateLabel(q.start)}\n\n- Check-in: 14h\n  ⬅️ Check-out: ${q.endWeek}, ${dateLabel(q.end)}\n- Check-out: 12h\n\n📊 Resumo da Reserva\n🌙 ${q.nights} ${q.nights===1?'noite':'noites'}\n👥 ${guests} ${Number(guests)===1?'pessoa':'pessoas'}\n❤️ Café da manhã incluído.\n\n💰 Valor Total: ${brl(q.total)}\n\n⚠️ *Tarifa não reembolsável.*\n\n📷 Imagens:\n${p.photos}\n\n✅ Para garantir a reserva, solicitamos o *pagamento de 50%* via PIX.\n\n✅ Os *50% restantes* deverão ser pagos no momento do check-in.\n\n🚨 *Importante:*\nEsta cotação é válida por 24 horas.\nApós esse período, será necessário verificar novamente a disponibilidade e a tarifa.\n\nAguardamos você! 🌟`; $('quoteText').value=text; $('quoteOutput').classList.remove('hidden'); }catch(error){ alert(error.message); } }
const loftMessage=n=>`Olá! Tudo bem? 😊\n\nAqui é da Pousada Casa Centro. Estamos entrando em contacto para confirmar a sua chegada ao Loft ${String(n).padStart(2,'0')}.\n\nPode informar, por favor, o horário aproximado de chegada? Assim deixamos tudo preparado para receber você.\n\nAguardamos você!`;
function calculate(){ const total=Number($('calcTotal').value)||0, percent=Number($('calcPercent').value)||0, fee=total*percent/100; $('calcResult').innerHTML=`<span>Base de cálculo: ${brl(total)} · ${percent}%</span><strong>Desconto/Comissão: ${brl(fee)}<br><b>Valor Final: ${brl(total-fee)}</b></strong>`; }
function convert(){ const rates={USD:.18,EUR:.17,ARS:190}, currency=$('currency').value, value=Number($('currencyValue').value)||0; $('currencyResult').innerHTML=`<span>Referência média ${currency}</span><strong>${(value*rates[currency]).toLocaleString('pt-BR',{minimumFractionDigits:2,maximumFractionDigits:2})} ${currency}</strong><small>Estimativa; confirme a taxa nas referências.</small>`; }
function copyText(value,button){ navigator.clipboard?.writeText(value); const old=button.textContent; button.textContent='Copiado'; setTimeout(()=>button.textContent=old,1400); }
renderProperties(); renderCalendar(); $('todayLabel').textContent=new Date(2026,7,20).toLocaleDateString('pt-BR',{weekday:'long',day:'2-digit',month:'long',year:'numeric'}).toUpperCase();
$('prevMonth').onclick=()=>{viewDate.setMonth(viewDate.getMonth()-1);renderCalendar()}; $('nextMonth').onclick=()=>{viewDate.setMonth(viewDate.getMonth()+1);renderCalendar()}; $('generateQuote').onclick=generateQuote; $('copyQuote').onclick=e=>copyText($('quoteText').value,e.target); ['calcTotal','calcPercent'].forEach(id=>$(id).oninput=calculate); ['currencyValue','currency'].forEach(id=>$(id).oninput=convert); calculate(); convert();
$('loftButtons').innerHTML=Array.from({length:8},(_,i)=>`<button class="${i===0?'active':''}" data-loft="${i+1}">${String(i+1).padStart(2,'0')}</button>`).join(''); $('loftButtons').onclick=e=>{if(e.target.dataset.loft){selectedLoft=Number(e.target.dataset.loft);document.querySelectorAll('#loftButtons button').forEach(b=>b.classList.toggle('active',b===e.target));$('loftLabel').textContent=`Loft ${String(selectedLoft).padStart(2,'0')}`}}; $('copyLoft').onclick=e=>copyText(loftMessage(selectedLoft),e.target);

const skinByName={luli:'theme-luli',christiano:'theme-christiano',ana:'theme-ana',joanna:'theme-joanna',recepção:'theme-recepcao',recepcao:'theme-recepcao','g hotelaria':'theme-deluxe','g hotelária':'theme-deluxe'};
function applySkin(name){ const clean=(name||'').trim(), key=clean.toLowerCase(), theme=skinByName[key]||''; document.body.classList.remove('theme-luli','theme-christiano','theme-ana','theme-joanna','theme-recepcao','theme-deluxe'); if(theme) document.body.classList.add(theme); $('greeting').textContent=clean?`Olá, ${clean}`:'Olá'; if(clean) localStorage.setItem('gHotelariaName',clean); else localStorage.removeItem('gHotelariaName'); }
const savedName=localStorage.getItem('gHotelariaName')||''; $('userName').value=savedName; applySkin(savedName); $('userName').addEventListener('input',e=>applySkin(e.target.value)); $('userName').addEventListener('change',e=>applySkin(e.target.value));
