const pousadas = [
  { name:'Centro Class', address:'R. Rui Barbosa, 08 - Centro, Armação dos Búzios - RJ', map:'https://maps.app.goo.gl/sF6QJmEnK5qKA7ji8', photos:'https://photos.app.goo.gl/HizRbSCCoEL75sqh9', cloudbeds:'http://hotels.cloudbeds.com/connect/208581#/calendar', color:'blue' },
  { name:'Casa Centro', address:'R. Rui Barbosa, 390 A - Lot. Triangulo de Buzios, Armação dos Búzios', map:'https://maps.app.goo.gl/guP7PDbX854PmhmZ6', photos:'https://photos.app.goo.gl/3JPDo4cmN8kzXSZU6', cloudbeds:'http://hotels.cloudbeds.com/connect/207758#/calendar', color:'terracotta' },
  { name:'Centro Up', address:'R. Rui Barbosa, 229 A - Lot. Triangulo de Buzios, Armação dos Búzios', map:'https://maps.app.goo.gl/8LPvmBV2XCA1wKNP9', photos:'https://photos.app.goo.gl/dpSKEJCMKNFF7jJE7', cloudbeds:'http://hotels.cloudbeds.com/connect/209202#/calendar', color:'sage' },
  { name:'Solar João Fernandes', address:'Rua São Cristóvão, R. João Fernandes, 16, Armação dos Búzios - RJ', map:'https://maps.app.goo.gl/qszQTRjtk92Pnfkn6', photos:'https://photos.app.goo.gl/ez61zesWzVXZFh388', cloudbeds:'http://hotels.cloudbeds.com/connect/239462#/calendar', color:'sand' }
];
const feriados = [
  ['2026-09-07','Independência do Brasil'],['2026-10-12','Nossa Senhora Aparecida'],['2026-11-02','Finados'],['2026-11-15','Proclamação da República'],['2026-11-20','Consciência Negra'],['2026-12-25','Natal'],['2027-01-01','Confraternização Universal']
];
const brl = value => Number(value || 0).toLocaleString('pt-BR',{style:'currency',currency:'BRL'});
const $ = id => document.getElementById(id);
let viewDate = new Date(2026,7,20), selectedLoft = 1;

function updateRoomOptions(){ const solar=Number($('quoteProperty').value)===3, options=solar?['Quadruple','Sextuple']:['Duplo Standard','Triplo'], current=$('quoteRoom').value; $('quoteRoom').innerHTML=options.map(room=>`<option value="${room}">${room}</option>`).join(''); if(options.includes(current)) $('quoteRoom').value=current; }
function renderProperties(){ $('propertyGrid').innerHTML = pousadas.map((p,i)=>`<a class="property ${p.color}" href="${p.cloudbeds}" target="_blank" rel="noopener"><span class="property-number">0${i+1}</span><h3>${p.name}</h3><p>Cloudbeds · calendário</p><span class="open">Abrir painel ↗</span></a>`).join(''); $('quoteProperty').innerHTML = pousadas.map((p,i)=>`<option value="${i}">${p.name}</option>`).join(''); updateRoomOptions(); }
function dateLabel(date){ return date.toLocaleDateString('pt-BR',{day:'2-digit',month:'2-digit',year:'numeric'}); }
function renderCalendar(){ const month=viewDate.getMonth(), year=viewDate.getFullYear(); $('monthLabel').textContent=viewDate.toLocaleDateString('pt-BR',{month:'long',year:'numeric'}); const first=(new Date(year,month,1).getDay()+6)%7, total=new Date(year,month+1,0).getDate(); let html=''; for(let i=0;i<first;i++) html+='<span class="day empty"></span>'; for(let day=1;day<=total;day++){ const key=`${year}-${String(month+1).padStart(2,'0')}-${String(day).padStart(2,'0')}`, holiday=feriados.find(x=>x[0]===key), today=key==='2026-08-20'; html+=`<button class="day ${holiday?'holiday':''} ${today?'today':''}" title="${holiday?holiday[1]:''}">${day}${holiday?'<i></i>':''}</button>`; } $('calendarGrid').innerHTML=html; const upcoming=feriados.filter(x=>new Date(x[0]+'T12:00:00')>=viewDate).slice(0,3); $('eventsList').innerHTML=upcoming.map(x=>{const d=new Date(x[0]+'T12:00:00');return `<div class="event"><strong>${String(d.getDate()).padStart(2,'0')}<small>${d.toLocaleDateString('pt-BR',{month:'short'}).replace('.','').toUpperCase()}</small></strong><span>${x[1]}<small>Feriado nacional</small></span></div>`}).join(''); const next=feriados.find(x=>new Date(x[0]+'T12:00:00')>=new Date(2026,7,20)); $('nextHoliday').textContent=next?`${new Date(next[0]+'T12:00:00').toLocaleDateString('pt-BR',{day:'2-digit',month:'long'})} · ${next[1]}`:''; $('selectedHoliday').textContent=upcoming[0]?upcoming[0][1]:''; }
function parseQuote(text){ const totalMatch=text.match(/Total da Acomodação\s*:?\s*(?:R\$\s*)?([\d.,]+)/i), dateLine=(text.match(/^.*\s[-–]\s.*$/m)||[])[0]||text.split(/\r?\n/)[0], parts=dateLine.split(/\s+[-–]\s+/); if(parts.length<2||!totalMatch) throw new Error('Não encontrei as datas e o Total da Acomodação.'); const months={jan:0,january:0,ene:0,enero:0,fev:1,feb:1,february:1,mar:2,march:2,abr:3,apr:3,april:3,mai:4,may:4,mai:4,jun:5,june:5,jul:6,july:6,ago:7,aug:7,august:7,set:8,sep:8,sept:8,september:8,oct:9,out:9,nov:10,dec:11,dez:11}; const parseSide=side=>{ const clean=side.trim().replace(/\s+/g,' '), week=(clean.match(/^([A-Za-zÀ-ÿ]{2,9})/)||[])[1]||''; const numeric=clean.match(/(\d{1,2})\/(\d{1,2})\/(\d{4})/); if(numeric) return {date:new Date(Number(numeric[3]),Number(numeric[2])-1,Number(numeric[1])),week}; const monthPattern='jan(?:uary)?|ene(?:ro)?|fev|feb(?:ruary)?|mar(?:ch)?|abr|apr(?:il)?|mai|may|jun(?:e)?|jul(?:y)?|ago|aug(?:ust)?|set|sep(?:t)?(?:ember)?|out|oct|nov|dez|dec'; const monthMatch=clean.match(new RegExp('('+monthPattern+')\\.?\\s+(\\d{1,2})(?:,?\\s+(\\d{4}))?','i')); if(!monthMatch) return null; const monthKey=monthMatch[1].toLowerCase().slice(0,3), year=Number(monthMatch[3]||2026); return {date:new Date(year,months[monthKey],Number(monthMatch[2])),week}; }; const startInfo=parseSide(parts[0]), endInfo=parseSide(parts[1]); if(!startInfo||!endInfo||Number.isNaN(startInfo.date.getTime())||Number.isNaN(endInfo.date.getTime())) throw new Error('Não consegui interpretar as datas da estadia.'); const start=startInfo.date,end=endInfo.date; if(end<=start) end.setFullYear(start.getFullYear()+1); const money=totalMatch[1].includes(',')?totalMatch[1].replace(/\./g,'').replace(',','.'):totalMatch[1].replace(/,/g,''); return {start,end,nights:Math.max(1,Math.round((end-start)/86400000)),total:Number(money),startWeek:startInfo.week,endWeek:endInfo.week}; }
const quoteLocale={
  pt:{address:'Endereço',location:'Localização',room:{'Duplo Standard':'Duplo Standard','Triplo':'Triplo','Quadruple':'Quadruplo','Sextuple':'Sêxtuplo'},dates:'Datas da Estadia',checkin:'Check-in',checkout:'Check-out',summary:'Resumo da Reserva',night:'noite',nights:'noites',guest:'pessoa',guests:'pessoas',breakfast:'Café da manhã incluído.',total:'Valor Total',nonRefundable:'Tarifa não reembolsável.',photos:'Imagens',secure:'Para garantir a reserva, solicitamos o *pagamento de 50%* via PIX.',remaining:'Os *50% restantes* deverão ser pagos no momento do check-in.',important:'Importante',valid:'Esta cotação é válida por 24 horas.',after:'Após esse período, será necessário verificar novamente a disponibilidade e a tarifa.',welcome:'Aguardamos você! 🌟',timeIn:'14h',timeOut:'12h'},
  en:{address:'Address',location:'Location',room:{'Duplo Standard':'Standard Double Room','Triplo':'Triple Room','Quadruple':'Quadruple Room','Sextuple':'Sextuple Room'},dates:'Stay Dates',checkin:'Check-in',checkout:'Check-out',summary:'Reservation Summary',night:'night',nights:'nights',guest:'guest',guests:'guests',breakfast:'Breakfast included.',total:'Total Amount',nonRefundable:'Non-refundable rate.',photos:'Photos',secure:'To secure your reservation, we require a *50% payment* via PIX.',remaining:'The *remaining 50%* must be paid at check-in.',important:'Important',valid:'This quote is valid for 24 hours.',after:'After this period, availability and rates must be checked again.',welcome:'We look forward to welcoming you! 🌟',timeIn:'2:00 PM',timeOut:'12:00 PM'},
  es:{address:'Dirección',location:'Ubicación',room:{'Duplo Standard':'Habitación Doble Estándar','Triplo':'Habitación Triple','Quadruple':'Habitación Cuádruple','Sextuple':'Habitación Séxtuple'},dates:'Fechas de la Estadía',checkin:'Check-in',checkout:'Check-out',summary:'Resumen de la Reserva',night:'noche',nights:'noches',guest:'persona',guests:'personas',breakfast:'Desayuno incluido.',total:'Valor Total',nonRefundable:'Tarifa no reembolsable.',photos:'Imágenes',secure:'Para garantizar la reserva, solicitamos el *pago del 50%* mediante PIX.',remaining:'El *50% restante* deberá ser abonado al momento del check-in.',important:'Importante',valid:'Esta cotización es válida por 24 horas.',after:'Después de este período, será necesario verificar nuevamente la disponibilidad y la tarifa.',welcome:'¡Esperamos recibirte! 🌟',timeIn:'14:00 h',timeOut:'12:00 h'},
  it:{address:'Indirizzo',location:'Posizione',room:{'Duplo Standard':'Camera Doppia Standard','Triplo':'Camera Tripla','Quadruple':'Camera Quadrupla','Sextuple':'Camera Sestupla'},dates:'Date del Soggiorno',checkin:'Check-in',checkout:'Check-out',summary:'Riepilogo della Prenotazione',night:'notte',nights:'notti',guest:'persona',guests:'persone',breakfast:'Colazione inclusa.',total:'Importo Totale',nonRefundable:'Tariffa non rimborsabile.',photos:'Immagini',secure:'Per garantire la prenotazione, richiediamo un *pagamento del 50%* tramite PIX.',remaining:'Il *50% restante* dovrà essere pagato al momento del check-in.',important:'Importante',valid:'Questo preventivo è valido per 24 ore.',after:'Dopo questo periodo, sarà necessario verificare nuovamente disponibilità e tariffa.',welcome:'Non vediamo l’ora di darti il benvenuto! 🌟',timeIn:'14:00',timeOut:'12:00'}
};
const weekdayNames={pt:['Dom','Seg','Ter','Qua','Qui','Sex','Sáb'],en:['Sun','Mon','Tue','Wed','Thu','Fri','Sat'],es:['Dom','Lun','Mar','Mié','Jue','Vie','Sáb'],it:['Dom','Lun','Mar','Mer','Gio','Ven','Sab']};
const monthNames={en:['Jan','Feb','Mar','Apr','May','Jun','Jul','Aug','Sep','Oct','Nov','Dec'],it:['gen','feb','mar','apr','mag','giu','lug','ago','set','ott','nov','dic']};
function quoteDate(date,lang){const dd=String(date.getDate()).padStart(2,'0'), mm=String(date.getMonth()+1).padStart(2,'0'), yyyy=date.getFullYear(), day=weekdayNames[lang][date.getDay()]; if(lang==='en') return `${day}, ${monthNames.en[date.getMonth()]} ${date.getDate()}, ${yyyy}`; return `${day}, ${dd}/${mm}/${yyyy}`;}
function quoteMoney(value,lang){return lang==='en'?`R$ ${Number(value).toLocaleString('en-US',{minimumFractionDigits:2,maximumFractionDigits:2})}`:brl(value);}
function generateQuote(){ try{ const p=pousadas[Number($('quoteProperty').value)], q=parseQuote($('quoteInput').value), guests=$('quoteGuests').value, selectedRoom=$('quoteRoom').value, selectedLanguage=$('quoteLanguage').value.toLowerCase(), lang=selectedLanguage==='en'||selectedLanguage.includes('english')?'en':selectedLanguage==='es'||selectedLanguage.includes('español')||selectedLanguage.includes('espanol')?'es':selectedLanguage==='it'||selectedLanguage.includes('italiano')?'it':'pt', t=quoteLocale[lang], room=t.room[selectedRoom]||selectedRoom, nightsLabel=q.nights===1?t.night:t.nights, guestsLabel=Number(guests)===1?t.guest:t.guests; const text=`🏡 POUSADA ${p.name.toUpperCase()}\n📍 ${t.address}: ${p.address}\n📍 ${t.location}: ${p.map}\n\n🛏️ **${room}**\n\n📅 **${t.dates}**\n➡️ ${t.checkin}: ${quoteDate(q.start,lang)}\n\n- ${t.checkin}: ${t.timeIn}\n  ⬅️ ${t.checkout}: ${quoteDate(q.end,lang)}\n- ${t.checkout}: ${t.timeOut}\n\n📊 **${t.summary}**\n🌙 ${q.nights} ${nightsLabel}\n👥 ${guests} ${guestsLabel}\n❤️ ${t.breakfast}\n\n💰 **${t.total}: ${quoteMoney(q.total,lang)}**\n\n⚠️ *${t.nonRefundable}*\n\n📷 **${t.photos}:**\n${p.photos}\n\n✅ ${t.secure}\n\n✅ ${t.remaining}\n\n🚨 *${t.important}:*\n${t.valid}\n${t.after}\n\n${t.welcome}`; $('quoteText').value=text; $('quoteOutput').classList.remove('hidden'); }catch(error){ alert(error.message); } }
const loftMessage=n=>`Olá! Tudo bem? 😊\n\nAqui é da Pousada Casa Centro. Estamos entrando em contacto para confirmar a sua chegada ao Loft ${String(n).padStart(2,'0')}.\n\nPode informar, por favor, o horário aproximado de chegada? Assim deixamos tudo preparado para receber você.\n\nAguardamos você!`;
function calculate(){ const total=Number($('calcTotal').value)||0, percent=Number($('calcPercent').value)||0, fee=total*percent/100; $('calcResult').innerHTML=`<span>Base de cálculo: ${brl(total)} · ${percent}%</span><strong>Desconto/Comissão: ${brl(fee)}<br><b>Valor Final: ${brl(total-fee)}</b></strong>`; }
function convert(){ const rates={USD:.18,EUR:.17,ARS:190}, currency=$('currency').value, value=Number($('currencyValue').value)||0; $('currencyResult').innerHTML=`<span>Referência média ${currency}</span><strong>${(value*rates[currency]).toLocaleString('pt-BR',{minimumFractionDigits:2,maximumFractionDigits:2})} ${currency}</strong><small>Estimativa; confirme a taxa nas referências.</small>`; }
function copyText(value,button){ navigator.clipboard?.writeText(value); const old=button.textContent; button.textContent='Copiado'; setTimeout(()=>button.textContent=old,1400); }
renderProperties(); $('quoteProperty').addEventListener('change',updateRoomOptions); renderCalendar(); $('todayLabel').textContent=new Date(2026,7,20).toLocaleDateString('pt-BR',{weekday:'long',day:'2-digit',month:'long',year:'numeric'}).toUpperCase();
$('prevMonth').onclick=()=>{viewDate.setMonth(viewDate.getMonth()-1);renderCalendar()}; $('nextMonth').onclick=()=>{viewDate.setMonth(viewDate.getMonth()+1);renderCalendar()}; $('generateQuote').onclick=generateQuote; $('copyQuote').onclick=e=>copyText($('quoteText').value,e.target); ['calcTotal','calcPercent'].forEach(id=>$(id).oninput=calculate); ['currencyValue','currency'].forEach(id=>$(id).oninput=convert); calculate(); convert();
$('loftButtons').innerHTML=Array.from({length:8},(_,i)=>`<button class="${i===0?'active':''}" data-loft="${i+1}">${String(i+1).padStart(2,'0')}</button>`).join(''); $('loftButtons').onclick=e=>{if(e.target.dataset.loft){selectedLoft=Number(e.target.dataset.loft);document.querySelectorAll('#loftButtons button').forEach(b=>b.classList.toggle('active',b===e.target));$('loftLabel').textContent=`Loft ${String(selectedLoft).padStart(2,'0')}`}}; $('copyLoft').onclick=e=>copyText(loftMessage(selectedLoft),e.target);

const skinByName={luli:'theme-luli',christiano:'theme-christiano',ana:'theme-ana',joanna:'theme-joanna',recepção:'theme-recepcao',recepcao:'theme-recepcao','g hotelaria':'theme-deluxe','g hotelária':'theme-deluxe'};
function applySkin(name){ const clean=(name||'').trim(), key=clean.toLowerCase(), theme=skinByName[key]||''; document.body.classList.remove('theme-luli','theme-christiano','theme-ana','theme-joanna','theme-recepcao','theme-deluxe'); if(theme) document.body.classList.add(theme); $('greeting').textContent=clean?`Olá, ${clean}`:'Olá'; if(clean) localStorage.setItem('gHotelariaName',clean); else localStorage.removeItem('gHotelariaName'); }
const savedName=localStorage.getItem('gHotelariaName')||''; $('userName').value=savedName; applySkin(savedName); $('userName').addEventListener('input',e=>applySkin(e.target.value)); $('userName').addEventListener('change',e=>applySkin(e.target.value));
